version: '3.7'

networks:
    webdavserver:
      ipam:
        driver: default

services:
    postgres-webdavserver:
        image: postgres:14
        container_name: postgres-webdavserver
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "CoreProject"
        networks:
            - webdavserver
        logging:
            driver: json-file
